name: Find Modified Python Files

on:
  push:
    branches:
      - main  

jobs:
  find_modified_files:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make script executable
        run: chmod +x scripts/find_modified_py_files_2.sh

      - name: Run script to find modified .py files
        run: |
          ./scripts/find_modified_py_files_2.sh
          mv -f modified_py_files.txt $GITHUB_WORKSPACE/modified_py_files.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: modified-py-files
          path: $GITHUB_WORKSPACE/modified_py_files.txt

  view_modified_files:
    needs: [find_modified_files]
    runs-on: self-hosted

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: modified-py-files
          path: ${{ github.workspace }}/artifacts

      - name: Print file contents
        run: cat ${{ github.workspace }}/artifacts/modified_py_files.txt