name: Track Code Changes

on:
  push:
    branches:
      - main

jobs:
  track-code-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract commit hash
        id: extract_commit_hash
        run: echo "${{ github.sha }}"

      - name: Save commit hash to file
        id: save_commit_hash
        run: echo "${{ steps.extract_commit_hash.outputs.output }}" > changelog.txt

      - name: View changed files
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }}

      - name: Log changes
        run: |
          echo "Changes detected:"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }}
